/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-11-25 08:43:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class landing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/ansh.sharma/.m2/repository/taglibs/standard/1.1.2/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.7.RELEASE.jar", Long.valueOf(1731130829267L));
    _jspx_dependants.put("jar:file:/C:/Users/ansh.sharma/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1488337488000L));
    _jspx_dependants.put("jar:file:/C:/Users/ansh.sharma/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1488337488000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1731907647344L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Parking Allocation System</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("  <link rel=\"icon\" href=\"static/images/logo.jpg\" type=\"image/jpg\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: 'Roboto', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    .hero-bg {\r\n");
      out.write("      background: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)),\r\n");
      out.write("      url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/bg.jpg');\r\n");
      out.write("      background-size: cover;\r\n");
      out.write("      background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("    .feature-icon {\r\n");
      out.write("      width: 60px;\r\n");
      out.write("      height: 60px;\r\n");
      out.write("      background-color: #4299e1;\r\n");
      out.write("      color: white;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      font-size: 24px;\r\n");
      out.write("    }\r\n");
      out.write("    .pricing-card {\r\n");
      out.write("      border: 1px solid #e2e8f0;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);\r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .pricing-card:hover {\r\n");
      out.write("      transform: translateY(-5px);\r\n");
      out.write("    }\r\n");
      out.write("    .feature-image {\r\n");
      out.write("      height: 200px;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    .steps-card {\r\n");
      out.write("      transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .steps-card:hover {\r\n");
      out.write("      transform: translateY(-10px);\r\n");
      out.write("      box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <header class=\"bg-white text-gray-900 py-4 shadow\" style=\"position:sticky; top:0%; padding: 1rem 2rem;\">\r\n");
      out.write("     <div class=\"flex justify-between items-center\">\r\n");
      out.write("       <div class=\"text-2xl font-bold flex items-center\">\r\n");
      out.write("         <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/logo.jpg\" alt=\"Logo\" style=\"height:40px; width:40px;\" class=\"mr-2\">\r\n");
      out.write("         Parking Allocation System\r\n");
      out.write("       </div>\r\n");
      out.write("       <nav>\r\n");
      out.write("         ");
      if (_jspx_meth_s_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         ");
      if (_jspx_meth_s_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         <ul class=\"flex space-x-4\">\r\n");
      out.write("           <li><a href=\"#\" class=\"text-gray-600 px-4 py-3 rounded-lg transition-all duration-300 hover:bg-blue-500 hover:text-gray-900\">\r\n");
      out.write("             <i class=\"fas fa-home\"></i> Home</a></li>\r\n");
      out.write("           <li><a href=\"#features\" class=\"text-gray-600 px-4 py-3 rounded-lg transition-all duration-300 hover:bg-blue-500 hover:text-gray-900\">\r\n");
      out.write("             <i class=\"fas fa-star\"></i> Features</a></li>\r\n");
      out.write("           <li><a href=\"#how-it-works\" class=\"text-gray-600 px-4 py-3 rounded-lg transition-all duration-300 hover:bg-blue-500 hover:text-gray-900\">\r\n");
      out.write("             <i class=\"fas fa-info-circle\"></i> How It Works</a></li>\r\n");
      out.write("           <li><a href=\"#pricing\" class=\"text-gray-600 px-4 py-3 rounded-lg transition-all duration-300 hover:bg-blue-500 hover:text-gray-900\">\r\n");
      out.write("             <i class=\"fas fa-dollar-sign money-icon\"></i> Pricing</a></li>\r\n");
      out.write("           <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"text-gray-600 px-4 py-3 rounded-lg transition-all duration-300 hover:bg-blue-500 hover:text-gray-900\">\r\n");
      out.write("             <i class=\"fas fa-sign-in-alt\"></i> Login</a></li>\r\n");
      out.write("           <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_reg_form}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"text-gray-600 px-4 py-3 rounded-lg transition-all duration-300 hover:bg-blue-500 hover:text-gray-900\">\r\n");
      out.write("             <i class=\"fas fa-user-plus\"></i> Register</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("       </nav>\r\n");
      out.write("     </div>\r\n");
      out.write(" </header>\r\n");
      out.write("\r\n");
      out.write("  <main>\r\n");
      out.write("    <section class=\"hero-bg py-32\">\r\n");
      out.write("      <div class=\"container mx-auto px-4 text-white text-center\">\r\n");
      out.write("        <h1 class=\"text-5xl font-bold mb-4\">Parking Allocation System</h1>\r\n");
      out.write("        <p class=\"text-xl mb-8\">Our platform streamlines the parking experience for customers.</p>\r\n");
      out.write("        <div class=\"flex justify-center space-x-4\">\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"bg-blue-500 hover:bg-blue-600 text-white py-3 px-6 rounded-md inline-block transition duration-300\">\r\n");
      out.write("            <i class=\"fas fa-user-plus mr-2\"></i>Get Started\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"#features\" class=\"bg-transparent border-2 border-white hover:bg-white hover:text-gray-900 text-white py-3 px-6 rounded-md inline-block transition duration-300\">\r\n");
      out.write("            <i class=\"fas fa-info-circle mr-2\"></i>Learn More\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"features\" class=\"py-16\">\r\n");
      out.write("      <div class=\"container mx-auto px-4\">\r\n");
      out.write("        <h2 class=\"text-3xl font-bold mb-12 text-center\">Key Features</h2>\r\n");
      out.write("        <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("          <div class=\"text-center\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/register.jpg\" alt=\"User Registration\" class=\"feature-image mb-4 mx-auto\" style=\"width: auto; height: 150px;\">\r\n");
      out.write("            <div class=\"feature-icon mx-auto mb-4\">\r\n");
      out.write("              <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-2\">User Registration</h3>\r\n");
      out.write("            <p class=\"text-gray-600\">Allow users to easily register and manage their parking accounts.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text-center\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/vehicle.jpg\" alt=\"Vehicle Registration\" class=\"feature-image mb-4 mx-auto\" style=\"width: auto; height: 150px;\">\r\n");
      out.write("            <div class=\"feature-icon mx-auto mb-4\">\r\n");
      out.write("              <i class=\"fas fa-car\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-2\">Vehicle Registration</h3>\r\n");
      out.write("            <p class=\"text-gray-600\">Users can register their vehicles and view their details.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text-center\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/booking.jpg\" alt=\"Slot Booking\" class=\"feature-image mb-4 mx-auto\" style=\"width: auto; height: 150px;\">\r\n");
      out.write("            <div class=\"feature-icon mx-auto mb-4\">\r\n");
      out.write("              <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-2\">Slot Booking</h3>\r\n");
      out.write("            <p class=\"text-gray-600\">Users can easily book available parking slots.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"bg-gray-100 py-16\">\r\n");
      out.write("      <div class=\"container mx-auto px-4\">\r\n");
      out.write("        <h2 class=\"text-3xl font-bold mb-12 text-center\">Our Benefits</h2>\r\n");
      out.write("        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-8\">\r\n");
      out.write("          <div class=\"flex items-center\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/parking.jpg\" alt=\"Parking Allocation\" class=\"rounded-lg w-full\" style=\"width: 300px; height: auto;\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"flex flex-col justify-center\">\r\n");
      out.write("            <h3 class=\"text-2xl font-bold mb-4\">Parking Allocation System</h3>\r\n");
      out.write("            <ul class=\"space-y-4\">\r\n");
      out.write("              <li class=\"flex items-center\">\r\n");
      out.write("                <i class=\"fas fa-check-circle text-green-500 mr-2\"></i>\r\n");
      out.write("                Real-time parking slot availability\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"flex items-center\">\r\n");
      out.write("                 <i class=\"fas fa-check-circle text-green-500 mr-2\"></i>\r\n");
      out.write("                  Pre-booking of Slots\r\n");
      out.write("                 </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"how-it-works\" class=\"py-16 bg-white\">\r\n");
      out.write("      <div class=\"container mx-auto px-4\">\r\n");
      out.write("        <h2 class=\"text-3xl font-bold mb-12 text-center\">How It Works</h2>\r\n");
      out.write("        <div class=\"grid grid-cols-1 md:grid-cols-4 gap-8\">\r\n");
      out.write("          <div class=\"text-center steps-card bg-gray-100 p-6 rounded-lg shadow-md\">\r\n");
      out.write("            <div class=\"w-24 h-24 bg-blue-500 text-white rounded-full flex items-center justify-center mx-auto mb-4 text-4xl\">\r\n");
      out.write("              <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-4\">Step 1: Register/Login</h3>\r\n");
      out.write("            <p class=\"text-gray-600 h-20\">Create an account or log in if you already have one.</p>\r\n");
      out.write("            <div class=\"mt-4 text-blue-500 font-semibold\">\r\n");
      out.write("              <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"text-center steps-card bg-gray-100 p-6 rounded-lg shadow-md\">\r\n");
      out.write("            <div class=\"w-24 h-24 bg-green-500 text-white rounded-full flex items-center justify-center mx-auto mb-4 text-4xl\">\r\n");
      out.write("              <i class=\"fas fa-car\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-4\">Step 2: Vehicle Registration</h3>\r\n");
      out.write("            <p class=\"text-gray-600 h-20\">Add your vehicle details to your profile.</p>\r\n");
      out.write("            <div class=\"mt-4 text-green-500 font-semibold\">\r\n");
      out.write("              <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"text-center steps-card bg-gray-100 p-6 rounded-lg shadow-md\">\r\n");
      out.write("            <div class=\"w-24 h-24 bg-purple-500 text-white rounded-full flex items-center justify-center mx-auto mb-4 text-4xl\">\r\n");
      out.write("              <i class=\"fas fa-parking\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-4\">Step 3: Book Your Slot</h3>\r\n");
      out.write("            <p class=\"text-gray-600 h-20\">Book the parking slot by the pricing preference.</p>\r\n");
      out.write("            <div class=\"mt-4 text-purple-500 font-semibold\">\r\n");
      out.write("              <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"text-center steps-card bg-gray-100 p-6 rounded-lg shadow-md\">\r\n");
      out.write("            <div class=\"w-24 h-24 bg-red-500 text-white rounded-full flex items-center justify-center mx-auto mb-4 text-4xl\">\r\n");
      out.write("              <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-4\">Step 4: Confirm Booking</h3>\r\n");
      out.write("            <p class=\"text-gray-600 h-20\">Review and confirm your parking slot reservation.</p>\r\n");
      out.write("            <div class=\"mt-4 text-red-500 font-semibold\">\r\n");
      out.write("                <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"pricing\" class=\"bg-gray-100 py-16\">\r\n");
      out.write("      <div class=\"container mx-auto px-4\">\r\n");
      out.write("        <h2 class=\"text-3xl font-bold mb-8 text-center\">Pricing</h2>\r\n");
      out.write("        <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("          <div class=\"pricing-card p-6 bg-white\">\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-4\">Hourly</h3>\r\n");
      out.write("            <p class=\"text-4xl font-bold mb-4\">₹10/hr</p>\r\n");
      out.write("            <ul class=\"text-gray-600 mb-8 space-y-2\">\r\n");
      out.write("              <li class=\"flex items-center\"><i class=\"fas fa-check text-green-500 mr-2\"></i>1 Parking Slot</li>\r\n");
      out.write("              <li class=\"flex items-center\"><i class=\"fas fa-check text-green-500 mr-2\"></i>Basic Features</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"bg-blue-500 hover:bg-blue-600 text-white py-3 px-6 rounded-md inline-block w-full text-center transition duration-300\">Join In</a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"pricing-card p-6 bg-white\">\r\n");
      out.write("              <h3 class=\"text-xl font-bold mb-4\">Daily</h3>\r\n");
      out.write("              <p class=\"text-4xl font-bold mb-4\">₹200/day</p>\r\n");
      out.write("              <ul class=\"text-gray-600 mb-8 space-y-2\">\r\n");
      out.write("                  <li class=\"flex items-center\"><i class=\"fas fa-check text-green-500 mr-2\"></i>1 Parking Slot</li>\r\n");
      out.write("                  <li class=\"flex items-center\"><i class=\"fas fa-check text-green-500 mr-2\"></i>Basic Features</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"bg-blue-500 hover:bg-blue-600 text-white py-3 px-6 rounded-md inline-block w-full text-center transition duration-300\">Join In</a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"pricing-card p-6 bg-white\">\r\n");
      out.write("            <h3 class=\"text-xl font-bold mb-4\">Monthly</h3>\r\n");
      out.write("            <p class=\"text-4xl font-bold mb-4\">₹4000/mo</p>\r\n");
      out.write("            <ul class=\"text-gray-600 mb-8 space-y-2\">\r\n");
      out.write("              <li class=\"flex items-center\"><i class=\"fas fa-check text-green-500 mr-2\"></i>Various Slots</li>\r\n");
      out.write("              <li class=\"flex items-center\"><i class=\"fas fa-check text-green-500 mr-2\"></i>Custom Features</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <a href=\"#\" class=\"bg-blue-500 hover:bg-blue-600 text-white py-3 px-6 rounded-md inline-block w-full text-center transition duration-300\">Coming Soon...</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"bg-gray-900 text-white py-8\">\r\n");
      out.write("    <div class=\"container mx-auto px-4\">\r\n");
      out.write("      <div class=\"grid grid-cols-1 md:grid-cols-4 gap-8\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4 class=\"text-lg font-bold mb-4\">About Us</h4>\r\n");
      out.write("          <p class=\"text-gray-400\">Parking Allocation System for the customers who needs to book slots.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4 class=\"text-lg font-bold mb-4\">Quick Links</h4>\r\n");
      out.write("          <ul class=\"space-y-2\">\r\n");
      out.write("            <li><a href=\"#\" class=\"text-gray-400 hover:text-white\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#features\" class=\"text-gray-400 hover:text-white\">Features</a></li>\r\n");
      out.write("            <li><a href=\"#how-it-works\" class=\"text-gray-400 hover:text-white\">How it works</a></li>\r\n");
      out.write("            <li><a href=\"#pricing\" class=\"text-gray-400 hover:text-white\">Pricing</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4 class=\"text-lg font-bold mb-4\">Support</h4>\r\n");
      out.write("          <ul class=\"space-y-2\">\r\n");
      out.write("            <li><a href=\"#\" class=\"text-gray-400 hover:text-white\">Help Center</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"text-gray-400 hover:text-white\">Privacy Policy</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"text-gray-400 hover:text-white\">Terms of Service</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4 class=\"text-lg font-bold mb-4\">Contact</h4>\r\n");
      out.write("          <ul class=\"space-y-2 text-gray-400\">\r\n");
      out.write("            <li><i class=\"fas fa-envelope mr-2\"></i>support@parking.com</li>\r\n");
      out.write("            <li><i class=\"fas fa-phone mr-2\"></i>+91 731 567 8900</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"border-t border-gray-800 mt-8 pt-8 text-center\">\r\n");
      out.write("       <p>&copy; 2024-2025 <a href=\"http://yash.com\" target=\"_blank\">YASH TECHNOLOGIES PVT LTD</a> | All Rights Reserved</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f0.setParent(null);
    // /WEB-INF/view/landing.jsp(68,9) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setVar("url_reg_form");
    // /WEB-INF/view/landing.jsp(68,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setValue("/reg_form");
    int[] _jspx_push_body_count_s_005furl_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
      if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f1 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f1.setParent(null);
    // /WEB-INF/view/landing.jsp(69,9) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setVar("url_login");
    // /WEB-INF/view/landing.jsp(69,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setValue("/index");
    int[] _jspx_push_body_count_s_005furl_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f1 = _jspx_th_s_005furl_005f1.doStartTag();
      if (_jspx_th_s_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f1.doFinally();
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f1);
    return false;
  }
}
